---
title: "About the course"
format: 
  html:
    code-fold: true
    code-tools: true
editor: source
---


The aim of the course is to make the participants acquainted with basic statistical ideas and methods. No special previous knowledge of mathematics or statistics is assumed. The statistical software R and the RStudio environment will be used in many of the exercises. Analysis of examples from biomedical research will be emphasized.


::: callout-note
## Use of the course material

This course website was built primarily with students taking MF9130E in mind, therefore the topics and examples are tailored to matche the existing teaching material we had been using at UiO.

However, the course material and website are **open source and fully publicly accessible**. We advocate strongly for **making learning statistics more accessible to everyone**. Feel free to spread the words! And do let us know if you benefit from the course and the website :)  

Please contact Chi Zhang [chi.zhang\@medisin.uio.no](mailto:chi.zhang@medisin.uio.no) if you have questions and feedbacks.

:::


#### Contact 2024 team

* Valeria Vitelli: [valeria.vitelli\@medisin.uio.no](mailto:valeria.vitelli@medisin.uio.no)
* Chi Zhang: [chi.zhang\@medisin.uio.no](mailto:chi.zhang@medisin.uio.no)

Please contact Chi regarding the development of the website.
