---
title: "Schedule"
format: 
  html:
    code-fold: true
    code-tools: true
editor: source
---



You can find the **official course schedule** provided by University of Oslo [here](https://www.uio.no/studier/emner/medisin/med/MF9130E/v24/timeplan/index.html). 
If there is an error in the time and place on this page, please refer to the official schedule.


::: callout-note

## Time and place

Sessions are roughly divided by AM (morning) and PM (afternoon). 

- AM: 8:30 - 11:45
- PM: 12:45 - 16:00

Locations

- **Aud13**: Auditorium 13 in Domus Medica ([map](https://use.mazemap.com/#v=1&config=uio&campusid=799&zlevel=2&center=10.715371,59.946743&zoom=18&sharepoitype=poi&sharepoi=1000983201))
- **Runde**: Runde auditorium R105 ([map](https://use.mazemap.com/#v=1&config=uio&campusid=799&zlevel=1&center=10.715886,59.946189&zoom=18&sharepoitype=poi&sharepoi=1001022929))

:::


# Week 1


|  Day | Session  | Place |  Topic           |  Course material        |
|:-------:|:---:|:------:|:---------------:|:-------------:|
| Day 1 - Apr 8 |PM | Aud 13 | **Course introduction** | [Lecture](v24/day1-1-Course_introduction.pdf)|
|           | | | **Data and descriptive statistics** |[Lecture](v24/day1-2-Data_and_descriptive_statistics.pdf) |
| Day 2 - Apr 9 |AM | Aud 13 | Lab 1 | [Lecture](v24/lab_20240409_intro_to_r.pdf), [Lab notes](lab/lab_intro_r.qmd), [Code](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/1_intro_r.R) |
|           | | | Lab 2 |[Lecture](v24/lab_20240409_descriptive.pdf), [Lab notes](lab/lab_eda_part1.qmd), [Code](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/2_eda_part1.R) |
|               |PM |  | **Intro to probability** |[Lecture](v24/lecture_20240409_probability.pdf) |
|           | | | **Diagnostic test** | [Lecture](v24/lecture_20240409_diagtest.pdf)|
|           | | | Lab 3 |[Lab notes](lab/lab_diagtest.qmd), [Code](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/2_diagtest.R) |
| Day 3 - Apr 10 |AM | Aud 13 | **Binomial distribution**  | [Lecture](v24/lecture_20240410_binom.pdf)|
|           | | | **Normal distribution** | [Lecture](v24/lecture_20240410_normaldist.pdf)|
|           | | | Lab 4 |[Lab notes](lab/lab_distribution.qmd), [Code](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/2_distributions.R)|
|               |PM |  | **Statistical inference I**  | [Lecture](v24/day3_Introductory_Lecture.pdf)|
|           | | | **Sample mean** | [Lecture](v24/day3_key_concept_1.pdf)|
|           | | | **Confidence interval** | [Lecture](v24/day3_key_concept_2.pdf) |
|           | | | **t-test** | [Lecture](v24/day3_key_concept_3.pdf)|
| Day 4 - Apr 11 |AM | Aud 13 | Lab 5 |[Lecture](v24/lab_20240411_ttest.pdf), [Lab notes](lab/lab_ttest.qmd), [Code](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/3_ttest.R) |
|                |PM |  | **Statistical inference II**  | [Lecture](v24/day4_Introductory_Lecture.pdf) |
|           | | | **One proportion** |[Lecture](v24/day4_key_concept_1.pdf)|
|           | | | **Two proportions** | [Lecture](v24/day4_key_concept_2.pdf) |
|           | | | **Table analysis** | [Lecture](v24/day4_key_concept_3.pdf)|
| Day 5 - Apr 12 |AM | Aud 13 | Lab 6 |[Lecture](v24/lab_20240412_categorical.pdf), [Lab notes](lab/lab_categorical.qmd), [Code](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/4_categorical.R) |







# Week 2


|  Day | Session  | Place |  Topic     |   Course material        |
|:-------:|:---:|:------:|:---------------:|:---------------:|
| Apr 22 |AM | Runde | Transformations | |
| | | | Non-parametric methods|  |
| | | | Lab 7 |[Lab notes](lab/lab_nonpara.qmd) |
|        |PM |  | Sample size and statistical power | Exercise|
| Apr 23 |AM | Runde | Study designs | |
|        |PM |  | Linear regression I |Lecture |
| | | | Lab 8 |[Lab notes](lab/lab_linearreg-I.qmd) |
| Apr 24 |AM | Aud 13 | Linear regression II | Lecture|
| | | | Lab 9| [Lab notes](lab/lab_linearreg-II.qmd)|
|        |PM |  | Linear regression III | Lecture|
| | | |Lab 10 | [Lab notes](lab/lab_linearreg-III.qmd)|
|        | |  | Course summary | Lecture|
| Apr 25 |AM | Runde | Logistic regression | Lecture|
| | | | Lab 11| [Lab notes](lab/lab_logistic_reg.qmd)|
|        |PM |  | Survival analysis | Lecture|
| | | |Lab 12 | [Lab notes](lab/lab_survival.qmd)|


