---
title: "Exercise - Categorical data analysis"
description: "Proportions, contingency table, chi-square test"
format: 
  html:
    code-fold: false
    code-tools: false
editor: source
---

Datasets

* Exercise 1: `PEFH98-english` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/PEFH98-english.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/PEFH98-english.csv))
* Exercise 2: `birth` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/birth.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/birth.csv))

[R Script](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/5_categorical.R)

------------------


## Exercise 1 (lung function)

Lung function has been measured on 106 medical students. Peak expiratory flow rate (PEF, measured in liters per minute) was measured three times in a sitting position, and three times in a standing position.

The variables are 

* Age (years)
* Gender (female, male)
* Height (cm)
* Weight (kg)
* PEF measured three times in a sitting position (pefsit1, pefsit2, pefsit3)
* PEF measured three times in a standing position (pefsta1, pefsta2, pefsta3)
* Mean of the three measurements made in a sitting position (pefsitm)
* Mean of the three measurements made in a standing position (pefstam)
* Mean of all six PEF values (pefmean)




#### 1a) 

We investigate whether having a high value of `pefmean` is associated with `gender`. 

First, create a new variable **highpef** that indicates whether `pefmean` is above 500.


#### 1b)

We investigate the association between these two variables via an appropriate table analysis. Make a table of `highpef` vs `gender`, which counts the number of subjects having each one of the four combinations in a 2 by 2 contingency table.



#### 1c)

Compute **risk ratio** and **odds ratio** (only the point estimates, no confidence interval). Here the exposure is `gender` (we assume that the reference group is *female*: unexposed), and outcome is `highpef`. Interpret your results. 

::: {.callout-tip collapse="true"}
## Risk ratio and odds ratio

|          | Outcome (yes) | Outcome (no) |
|----------|---------------|--------------|
| Exposed  | a             | b            |
| Unexposed| c             | d            |

Risk ratio: $\frac{a/(a+b)}{c/(c+d)}$

Odds ratio: $\frac{a/b}{c/d} = \frac{ad}{bc}$

:::


#### 1d) 

Carry out a chi-square analysis to assess the strength of association. Interpret your results.




## Exercise 2 (birth data)

We shall analyse the data set given in the file `birth.dta`. In a study in Massachusetts, USA, birth weight was measured for the children of 189 women. The main variable in the study was birth weight, `BWT`, which is an important indicator of the condition of a newborn child. Low birth weight (below 2500 g) may be a medical risk factor. A major question is whether smoking during pregnancy influences the birth weight. One has also studied whether a number of other factors are related to birth weight, such as hypertension in the mother. 

The variables of the study are

* Identification number (ID)
* Low birth weight 
* Age of the mother (AGE)
* Weight (in pounds) at last menstruaal period (LWT)
* Ethnicity, 1 means White, 2 means African American, 3 meaans other (ETH)
* Smoking status, 1 means current smoker, 0 means not smoking during pregnancy (SMK)
* History of premature labbour, values 0, 1, 2... (PTL)
* History of hypertension, 1 is yes, 0 is no (HT)
* Uterine irritability, 1 is yes, 0 is no (UI)
* First trimester visits, values 0, 1, 2... (FTV)
* Third trimster visits, values 0, 1, 2... (TTV)
* Birth weight (BWT)




#### 2a) 

Does smoking influence the birth weight of a baby? 

Make a histogram and a box plot, and find the median and mean for birth weight in grams (`bwt`) for the two groups of mothers: one group that smokes, and one that does not smoke durinng the pregnancy. (Hint: use variable `smk` for this task)


#### 2b)

Are the distributions for the two groups normal? Can we conclude that smoking has an effect on the weight of a newborn? Use a t-test.


#### 2c)

Do mothers of hypertension have a tendency to have babies with a lower birth weight? (The variable for hypertension is `ht`)

Make a histogram of birth weight for the two groups of mothers with and without hypertension. What do you observe?


#### 2d)

Analyse the effect of smoking on birth weight in a table (categorical analysis): compute the relative risk (risk ratio) and carry out a test to assess the strength of association. 

Also do it for hypertension (instead of smoking). 

What can you conclude?










