---
title: "Exercise - EDA (part I)"
description: "Exploring a dataset, basic data manipulation, descriptive statistics"
format: 
  html:
    code-fold: false
    code-tools: false
editor: source
---

## Exercise 1 (weight)

#### 1a 

Generate a variable named `weight`, with the following measurements:

```
50 75 70 74 95 83 65 94 66 65 65 75 84 55 73 68 72 67 53 65
```

#### 1b

Make a simple descriptive analysis of the variable, what are the mean, standard deviation, maximum, minimum and quantiles?

How to interpret the data?

#### 1c

Make a histogram.

#### 1d

Make a boxplot. What do the two dots on the top represent?



## Exercise 2 (lung function)

Lung function has been measured on 106 medical students. Peak expiratory flow rate (PEF, measured in liters per minute) was measured three times in a sittinng position, and three times in a standing position.

The variables are 

* Age (years)
* Gender (1 is female, 2 is male)
* Height (cm)
* Weight (kg)
* PEF measured three times in a sitting position (pefsit1, pefsit2, pefsit3)
* PEF measured three times in a standing position (pefsta1, pefsta2, pefsta3)
* Mean of the three measurements made in a sitting position (pefsitm)
* Mean of the three measurements made in a standing position (pefstam)
* Mean of all six PEF values (pefmean)

#### 2a) 

Download and open `PEFH98-english.dta` into R. 

If you have problem with `.dta` data format, you can also use `PEFH98-english.csv`.

Pay attention to how `gender` is coded. We might have to modify it. 

#### 2b)

How many observations are there (number of subjects)? How do you get a list of variable names from your dataset?

Make a histogram for each of the following variables. Compute means, and interpret the results.

```
height
weight
age
pefsitm
pefstam
```

#### 2c)

Make histograms for the variables `height` and `pefmean` for men and women separately. Also try to make boxplots.

What conclusion can you draw? 



#### 2d)

Make three scatterplots to compare 

* `pefmean` with `height`
* `pefmean` with `weight`
* `pefmean` with `age` 

What association do you see?









