---
title: "Exercise - Non-parametric tests"
description: "Wilcoxon signed rank, rank sum test"
format: 
  html:
    code-fold: false
    code-tools: true
editor: source
---

Datasets

* Exercise 1: `PEFH98-english` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/PEFH98-english.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/PEFH98-english.csv))
* Exercise 2: `liggetid` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/liggetid.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/liggetid.csv))
* Exercise 3: `antibody` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/antibody.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/antibody.csv))
* Exercise 4: `nausea` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/nausea.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/nausea.csv))



[R script](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/6_nonpara.R)

------------------


## Exercise 1 (lung function)

Lung function has been measured on 106 medical students. Peak expiratory flow rate (PEF, measured in liters per minute) was measured three times in a sittinng position, and three times in a standing position.

The variables are 

* Age (years)
* Gender (female, 2 male)
* Height (cm)
* Weight (kg)
* PEF measured three times in a sitting position (pefsit1, pefsit2, pefsit3)
* PEF measured three times in a standing position (pefsta1, pefsta2, pefsta3)
* Mean of the three measurements made in a sitting position (pefsitm)
* Mean of the three measurements made in a standing position (pefstam)
* Mean of all six PEF values (pefmean)


#### 1a) 

We shall consider the difference betweenn PEF measured in a sitting position and in a standing position, i.e. we look at `diff_pef = pefstam - pefsitm`.  First compute this variable. 


#### 1b) 

Make a histogram and Q-Q plot for the differences. 



#### 1c) 

Do a non-parametric test to decide whether `pefsitm` and `pefstam` are significantly different.


## Exercise 2 (length of hospital stay)

The data was collected at the Geriatric Department at Ullevål Sykehus. Below is a description of the data set `liggetid`. The file includes the following variables:

- Year of birth (faar)
- Month of birth (fmaan)
- Day of birth (fdag)
- Year of hospital admission (innaar)
- Month of admission (innmaan)
- Day of admission (inndag)
- Year of discharge from hospital (utaar)
- Month of discharge (utmaan)
- Day of discharge (utdag)
- Gender, where 1 = male and 0 = female (kjoenn)
- Admission from, where 1 = home, 2 = Div. of Medicine, 3 =
Div. of Surgery, 4 = Other division, 5 = Other hospital, 6 =
Nursing home (kom_fra)
- Stroke, where 1 = yes, 0 = no (slag)
- Age (alder)
- Hospital stay, in days (liggetid)
- Logarithm of hospital stay (lnliggti)
- Comes from Div. of Medicine (kom_fra2)
- Comes from Div. of Surgery (kom_fra3)
- Comes from Other division (kom_fra4)
- Comes from Other hospital (kom_fra5)
- Comes from Nursing home (kom_fra6)
- Censoring variable (censor)

The variable `liggetid` time is calculated from the `innaar`, `innmaan`, `inndag`, `utaar`, `utmaan` and `utdag` variables. 



#### 2a)

We want to compare the **length of hospital stay** for patients with and without **stroke**. First get a better understanding of the data. Start with computing some summary (descriptive) statistics for these two variables: 

* **mean, median, min, max, 75-th percentile** for length of hospital stay (`liggetid`);
* **count** of how many patient have stroke, and do not have stroke (`slag == 1` or `0`)

Visualize the variable `liggetid` using histogram and Q-Q plot, is the requirement for t-test met?


#### 2b) 

Since we want to compare the length of hospital stay for two groups, we need to separate the length of stay data into two groups, based on whether patients have stroke or not. Create two variables, `ligt_s1` and `ligt_s0`. 

Do an appropriate non-parametric test. What is the difference between this test and the one you did in Exercise 1?


::: {.callout-tip collapse="true"}
## Separate one variable via index and `which()`

Previously, we showed how to separate one variable based on another,

* Exercise 2c) in [EDA I](https://ocbe-uio.github.io/teaching_mf9130e/lab/lab_eda_part1.html)
* Exercise 2a) in [Categorical data analysis](https://ocbe-uio.github.io/teaching_mf9130e/lab/lab_categorical.html)

You can try to use this method here as well; but you might notice that there are some NA in the results. This is because when you do `stroke == 0` on NA, instead of giving you `T` or `F`, it gives `NA`; so the result of filtering `liggetid` keeps both `T` and `NA`. 

These NAs can be removed post-hoc; but a clearer solution is to set 2 conditions inside the square bracket, and combine with `&`. 

* `!is.na(stroke)` means stroke variable not NA
* `stroke == 1` means stroke variable equals to 1
* `which()` identifies the indices for stroke where the conditions were met, e.g. the 4th, 22th elements.

:::

#### 2c)


Do the same analysis with a t-test on the logarithm-transformed data. The transformed variable already exists in the data set as `lnliggti`.




## Exercise 3 (antibody)

(Baker et al., 1980) We have data on concentration of antibody of Type III Group B Streptococcus (GBS) in 20 volunteers before and after immunization. The dataset is `antibody`. 

#### 3a) 

The comparison of the antibody levels was summarized in the report of this study as '$t = 1.8; P > 0.05$'. Comment on the result. 

#### 3b)

Analyse the data with an appropriate test. Justify your choice. 




## Exercise 4 (nausea) 

(Williams et al., 1989) Patients receiving chemotherapy as outpatients were randomized to receive either an active antiemetic treatment or placebo. The following table shows measurements (in mm) on a 100mm linear analogue self-assessment scale for nausea. The dataset is `nausea`. 

* group: `1` is active (treatment), and `2` is placebo.

#### 4a)

Choose an appropriate test for comparing the treatment and placebo groups. Justify your choice. 





