---
title: "Survival analysis"
description: "Kaplan-Meier curve, log rank tests"
format: 
  html:
    code-fold: false
    code-tools: true
editor: source
---

Datasets

* Exercise 1: `melanoma`([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/melanoma.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/melanoma.csv))
* Exercise 2: `liggetid` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/liggetid.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/liggetid.csv))


[R script](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/10_survival.R)

------------------




# Exercise 1: Melanoma 

The data concern 205 patients with malignant melanoma who were operated at the university hospital in Odense, Denmark, in the period 1962-77. The patients were followed up to death or censored at the end of the study. We shall study the effect on survival of the patient’s gender and tumor thickness.

The variables included in the dataset are:

* status (1=death from disease, 2=censored, 4=death from other causes) 
* lifetime (years) from operation
* ulceration of tumor (1=yes, 2=no)
* tumor thickness in 1/100 mm
* gender (f=1, m=2)
* age at operation in years
* grouped tumor thickness (1: 0-1 mm, 2: 2-5 mm, 3: 5+ mm) 
* logarithm of tumor thickness


### 1a) 

The “event of interest” is defined as “death from disease”. Pre-process the variables that R will use for basic survival analysis as shown in class.


### 1b) 

Make a Kaplan-Meier plot of the survival curve. What are the estimated probabilities of surviving 1 year, 2 years, 5 years?

### 1c) 

Compare survival according to gender. Test the difference with a logrank test.


### 1d)

Study survival according to grouped tumor thickness by comparing survival curves in each group and test with a logrank test.



# Exercise 2: length of hospital stay 

The data was collected at the Geriatric Department at Ullevål Sykehus. Below is a description of the data set `liggetid`. The file includes the following variables:

- Year of birth (faar)
- Month of birth (fmaan)
- Day of birth (fdag)
- Year of hospital admission (innaar)
- Month of admission (innmaan)
- Day of admission (inndag)
- Year of discharge from hospital (utaar)
- Month of discharge (utmaan)
- Day of discharge (utdag)
- Gender, where 1 = male and 0 = female (kjoenn)
- Admission from, where 1 = home, 2 = Div. of Medicine, 3 =
Div. of Surgery, 4 = Other division, 5 = Other hospital, 6 =
Nursing home (kom_fra)
- Stroke, where 1 = yes, 0 = no (slag)
- Age (alder)
- Hospital stay, in days (liggetid)
- Logarithm of hospital stay (lnliggti)
- Comes from Div. of Medicine (kom_fra2)
- Comes from Div. of Surgery (kom_fra3)
- Comes from Other division (kom_fra4)
- Comes from Other hospital (kom_fra5)
- Comes from Nursing home (kom_fra6)
- Censoring variable (censor)

The variable `liggetid` time is calculated from the `innaar`, `innmaan`, `inndag`, `utaar`, `utmaan` and `utdag` variables. 

### 2a) 

Analyze the relationship between the variables `liggetid` and `kjoenn` with a Kaplan-Meier plot. Test the difference with a log-rank test.


### 2b) 

Analyze the relationship between the variables `liggetid` and `slag` with a Kaplan-Meier plot. Test the difference with a log-rank test.





