---
title: "Logistic regression"
description: "Logistic regression"
format: 
  html:
    code-fold: false
    code-tools: true
editor: source
---

Datasets

* Exercise 1: `birth` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/birth.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/birth.csv))

* Exercise 2: `framingham` ([rda link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/framingham.rda), [csv link](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/data/framingham.csv))



[R Script](https://github.com/ocbe-uio/teaching_mf9130e/blob/main/lab/code/9_logisticreg.R)

------------------


# Examples (exercises with solution)



(Dataset `birth` might be switched out)

```{r}
#| label: birth example
#| warning: false
#| echo: true


# load data
birth_data <- haven::read_dta('data/birth.dta')

# print the first rows of the data set
head(birth_data)



```

### Fit a logistic regression model for `low` and `age`

```{r}
#| label: birth example (2)
#| warning: false
#| echo: true

# low ~ age 

lr_low_age <- glm(low ~ age, data = birth_data, family = 'binomial')
summary(lr_low_age)

```


```{r}
#| label: birth example (3)
#| warning: false
#| echo: true

# the result regresssion coefficient is not odds ratio
lr_low_age$coefficients

# regression coefficients can also be extracted in this way:
coefficients(lr_low_age)
# coef(lr_low_age)

# confidence interval for age and intercept
confint(lr_low_age)
```

```{r}
#| label: birth example (4)
#| warning: false
#| echo: true

# to get odds ratio, exponentiate 
exp(coef(lr_low_age))
exp(confint(lr_low_age))

```